/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmConfigDialog: typeof import('./src/components/dialogs/AlarmConfigDialog.vue')['default']
    AlarmPanel: typeof import('./src/components/layout/AlarmPanel.vue')['default']
    CanvasConfigDialog: typeof import('./src/components/dialogs/CanvasConfigDialog.vue')['default']
    CanvasRuler: typeof import('./src/components/layout/CanvasRuler.vue')['default']
    ComponentPanel: typeof import('./src/components/layout/ComponentPanel.vue')['default']
    ContextMenu: typeof import('./src/components/layout/ContextMenu.vue')['default']
    CustomComponentDialog: typeof import('./src/components/dialogs/CustomComponentDialog.vue')['default']
    DataSourceDialog: typeof import('./src/components/dialogs/DataSourceDialog.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LayerPanel: typeof import('./src/components/layout/LayerPanel.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    MiniMap: typeof import('./src/components/layout/MiniMap.vue')['default']
    PropertyPanel: typeof import('./src/components/layout/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusRuleDialog: typeof import('./src/components/dialogs/StatusRuleDialog.vue')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
    TrendChartDialog: typeof import('./src/components/dialogs/TrendChartDialog.vue')['default']
  }
}
